import React from 'react';
import { ShieldAlert, Maximize2 } from 'lucide-react';
import Latex from '@/components/Latex';

export default function Section7_Effects() {
  return (
    <section id="effects" className="space-y-8 stagger scroll-mt-24 mt-16 border-t border-slate-800 pt-16">
      <header>
        <span className="claude-kicker text-teal-400">Section 3.7</span>
        <h2 className="text-3xl font-bold text-white mt-2">Other Effects: Artifacts & Distortion</h2>
        <p className="text-slate-400 mt-4 leading-relaxed">
          Beyond contrast, resolution, and noise, medical images can be degraded by two other important effects: artifacts and distortion. Both can severely impair correct detection and characterization of features of interest.
        </p>
      </header>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Artifacts */}
        <div className="claude-surface p-8">
           <h3 className="text-xl font-bold text-white flex items-center gap-2 mb-6">
              <ShieldAlert className="w-5 h-5 text-red-400" /> Artifacts
           </h3>
           <p className="text-slate-300 leading-relaxed mb-6">
             Artifacts are false features in an image that do not represent valid anatomical or functional objects. They add "clutter" to images.
           </p>
           
           <h4 className="text-white font-bold text-sm mb-3">Common CT Artifacts:</h4>
           <ul className="space-y-4">
             <li className="bg-slate-900 border border-slate-800 p-4 rounded-lg">
                <span className="text-red-400 font-bold block mb-1">Motion Artifacts</span>
                <span className="text-sm text-slate-400">Patient movement produces streak artifacts throughout the image.</span>
             </li>
             <li className="bg-slate-900 border border-slate-800 p-4 rounded-lg">
                <span className="text-red-400 font-bold block mb-1">Star Artifacts</span>
                <span className="text-sm text-slate-400">Generated by metallic materials in the patient, resulting in incomplete projections.</span>
             </li>
             <li className="bg-slate-900 border border-slate-800 p-4 rounded-lg">
                <span className="text-red-400 font-bold block mb-1">Beam Hardening</span>
                <span className="text-sm text-slate-400">Broad dark bands or streaks due to significant beam attenuation by certain materials.</span>
             </li>
             <li className="bg-slate-900 border border-slate-800 p-4 rounded-lg">
                <span className="text-red-400 font-bold block mb-1">Ring Artifacts</span>
                <span className="text-sm text-slate-400">Caused by detectors that go out of calibration.</span>
             </li>
           </ul>
        </div>

        {/* Distortion */}
        <div className="claude-surface p-8">
           <h3 className="text-xl font-bold text-white flex items-center gap-2 mb-6">
              <Maximize2 className="w-5 h-5 text-orange-400" /> Distortion
           </h3>
           <p className="text-slate-300 leading-relaxed mb-6">
             Distortion is geometrical in nature. It is the inability of a system to give an accurate impression of the shape, size, and/or position of objects.
           </p>
           
           <div className="space-y-6">
             <div className="border-l-2 border-orange-500 pl-4">
                <h4 className="text-orange-400 font-bold mb-1">Size Distortion (Magnification)</h4>
                <p className="text-sm text-slate-400 leading-relaxed">
                  In projection radiography, size distortion occurs due to the distance of the x-ray source from the object. Two objects of different sizes may have the exact same projection size on the detector if they are at different depths.
                </p>
             </div>
             <div className="border-l-2 border-orange-500 pl-4">
                <h4 className="text-orange-400 font-bold mb-1">Shape Distortion</h4>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Generated by unequal magnification. In radiography, it is caused by anatomical structures lying at different levels, or by the divergence of the x-ray beam.
                </p>
             </div>
           </div>
           
           <div className="mt-8 bg-slate-900 border border-slate-800 p-4 rounded text-sm text-slate-400 italic text-center">
             To correct distortion, knowledge of the actual object shape and the specific imaging geometry is required.
           </div>
        </div>
      </div>
    </section>
  );
}
