'use client';

import Link from 'next/link';
import { Target, Zap, Waves, Activity, AlertCircle, Layers, Fingerprint } from 'lucide-react';
import Latex from '@/components/Latex';

export default function Chapter5() {
  return (
    <div className="space-y-12 pb-20 fade-up">
      {/* Navigation */}
      <div className="flex items-center gap-4 text-sm text-slate-400">
        <Link href="/" className="hover:text-white transition-colors">Home</Link>
        <span>/</span>
        <span className="text-white">Chapter 5</span>
      </div>

      {/* Header */}
      <header className="border-b border-slate-800 pb-8 stagger">
        <span className="claude-kicker text-red-500">Section 5.1 - 5.5</span>
        <h1 className="text-5xl font-extrabold text-white mt-3 mb-6 tracking-tight">
          Projection Radiography
        </h1>
        <p className="text-xl text-slate-400 max-w-3xl leading-relaxed">
          The foundation of medical imaging. We explore the generation of X-rays, interactions with matter, the geometric principles of projection, and the engineering behind modern digital detectors.
        </p>
        <div className="flex gap-4 mt-6">
          <span className="claude-chip">
            <Zap className="w-4 h-4 mr-2 inline text-amber-400" /> X-Ray Physics
          </span>
          <span className="claude-chip">
            <Layers className="w-4 h-4 mr-2 inline text-blue-400" /> FPD Detectors
          </span>
        </div>
      </header>

      {/* X-Ray Tube & Exposure */}
      <section className="space-y-6 stagger">
        <span className="claude-kicker text-amber-400">Photon Generation</span>
        <h2 className="text-3xl font-bold text-white">The X-Ray Tube</h2>

        <div className="claude-surface p-8">
          <p className="text-slate-300 text-lg mb-8 leading-relaxed">
            X-rays are generated by accelerating electrons from a heated cathode filament into a dense tungsten anode node. The kinetic energy converts into Bremsstrahlung (braking radiation) and characteristic X-rays. <strong>Only 1% becomes X-rays; 99% is lost as heat.</strong>
          </p>

          <div className="grid md:grid-cols-2 gap-8">
            <div className="space-y-6">
              <div className="bg-slate-900 border border-slate-800 p-6 rounded-xl">
                <h3 className="text-amber-400 font-bold mb-3 flex items-center gap-2">
                  <Activity className="w-4 h-4" /> The mAs Parameter
                </h3>
                <p className="text-slate-300 text-sm leading-relaxed mb-4">
                  Tube current (mA) × exposure time (s) = mAs. This controls the total number of photons (quantity). <strong>Density Maintenance</strong> dictates that if you change distance, you must compensate mAs via the inverse square law:
                </p>
                <div className="bg-slate-950 p-4 rounded border border-slate-800 text-center">
                  <Latex formula="\text{mAs}_{\text{new}} = \text{mAs}_{\text{old}} \times \left(\frac{d_{\text{new}}}{d_{\text{old}}}\right)^2" displayMode />
                </div>
              </div>

              <div className="bg-slate-900 border border-slate-800 p-6 rounded-xl border-l-blue-500">
                <h3 className="text-blue-400 font-bold mb-3">Beam Hardening & Filtration</h3>
                <p className="text-slate-300 text-sm leading-relaxed">
                  The X-ray spectrum contains many useless, low-energy photons that only increase patient skin dose without reaching the detector. We use <strong>inherent</strong> (tube glass/oil) and <strong>added filtration</strong> (1-3mm Al or Cu) to absorb these soft rays, shifting the effective energy spectrum "harder" (higher energy).
                </p>
              </div>
            </div>

            <div className="claude-diagram bg-slate-950 p-6 rounded-xl flex flex-col justify-center gap-4 relative overflow-hidden h-full min-h-[300px]">
              <div className="absolute top-4 right-4 text-xs font-mono text-slate-500">kVp: 30-150</div>
              
              {/* Cathode */}
              <div className="w-16 h-8 bg-slate-800 border-2 border-amber-600/50 rounded-l-full self-start relative flex items-center justify-end pr-2">
                <div className="text-[10px] text-amber-500 font-bold absolute -top-5 left-2">Cathode (-)</div>
                <div className="w-4 h-4 rounded-full border-t-2 border-r-2 border-amber-400 -rotate-45"></div>
              </div>
              
              {/* Electron Stream */}
              <div className="h-20 flex px-8 gap-2 opacity-60 ml-4 relative">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-40 border-t-4 border-amber-400 border-dashed translate-x-12 opacity-50 shadow-[0_0_10px_#fbbf24]"></div>
                </div>
              </div>
              
              {/* Anode */}
              <div className="w-24 h-full absolute right-8 top-1/2 -translate-y-1/2 bg-slate-700 border-l-[12px] border-slate-500 transform skew-x-[20deg] flex items-center pb-12 rotate-[-5deg]">
                 <div className="text-[10px] text-slate-300 font-bold absolute top-10 -left-6 transform skew-x-[-20deg]">Anode (+)</div>
              </div>
              
              {/* X-Ray Beam Cone */}
              <div className="absolute right-[4rem] top-1/2 w-0 h-0 border-l-[60px] border-l-transparent border-r-[60px] border-r-transparent border-b-[150px] border-blue-500/20 transform rotate-180 z-10 translate-y-10"></div>
              <div className="absolute bottom-10 right-28 text-sm font-bold text-blue-400">X-Ray Beam</div>
            </div>
          </div>
        </div>
      </section>

      {/* Interactions & Contrast */}
      <section className="space-y-6 stagger">
        <span className="claude-kicker text-blue-400">Tissue Interactions</span>
        <h2 className="text-3xl font-bold text-white">K-Edge & Radiographic Contrast</h2>

        <div className="grid lg:grid-cols-[1.2fr_1fr] gap-8">
          <div className="claude-surface p-8 space-y-6">
             <p className="text-slate-300 text-sm leading-relaxed">
               Image contrast relies fundamentally on the photoelectric effect, which scales roughly as <Latex formula="Z^3/E^3" />. Bones appear bright because of Calcium (high <Latex formula="Z" />). However, for soft tissues (bowel, blood vessels), we must introduce heavy contrast agents.
             </p>

            <div className="claude-panel p-6 border-l-4 border-l-purple-500 bg-purple-950/10 mt-6">
              <h3 className="text-purple-400 font-bold mb-4 flex items-center gap-2">
                <Fingerprint className="w-4 h-4" /> The K-Edge Physics
              </h3>
              <p className="text-slate-300 text-sm leading-relaxed mb-4">
                Contrast agents like Iodine (Z=53) and Barium (Z=56) exhibit a dramatic, sudden spike in X-ray attenuation exactly when the photon energy matches the binding energy of their innermost K-shell electrons.
              </p>
              <ul className="text-xs text-slate-400 space-y-2 mt-4 ml-2">
                <li><span className="text-purple-400 font-bold">Iodine K-edge:</span> 33.2 keV</li>
                <li><span className="text-purple-400 font-bold">Barium K-edge:</span> 37.4 keV</li>
              </ul>
              <p className="text-[10px] text-slate-500 italic mt-4">
                By tuning the kVp so the average X-ray energy sits just above this K-edge, the contrast agent becomes massively opaque, lighting up vessels against the soft tissue background.
              </p>
            </div>
          </div>

          <div className="claude-diagram flex flex-col px-6 pt-12 pb-6 bg-slate-900 border border-slate-700 relative rounded-xl h-full items-end justify-end">
            <div className="absolute top-4 left-4 text-xs font-bold text-slate-400">Attenuation Coefficient (μ)</div>
            <div className="absolute bottom-4 right-1/2 text-xs font-bold text-slate-400">Photon Energy (keV)</div>
            
            {/* Chart Graph */}
            <div className="w-full h-[200px] border-l-2 border-b-2 border-slate-600 relative flex items-end ml-4 shadow-inner">
               {/* Soft Tissue Curve */}
               <svg className="absolute inset-0 w-full h-full" preserveAspectRatio="none">
                 <path d="M 0 50 Q 80 150 200 180" fill="none" stroke="#64748b" strokeWidth="2" strokeDasharray="4 4" />
               </svg>
               <span className="absolute top-1/2 right-12 text-[10px] text-slate-500">Soft Tissue</span>
               
               {/* Contrast Agent (Iodine) Curve */}
               <svg className="absolute inset-0 w-full h-full" preserveAspectRatio="none">
                 {/* Down curve, then huge vertical spike at x=80, then down again */}
                 <path d="M 0 180 Q 40 185 78 190 L 80 20 Q 140 120 200 160" fill="none" stroke="#a855f7" strokeWidth="3" />
               </svg>
               <span className="absolute top-4 left-[90px] text-xs font-bold text-purple-400">Iodine K-Edge<br/>(33.2 keV)</span>
               <div className="absolute bottom-0 left-[80px] w-0.5 h-full bg-purple-500/20 border-l border-dashed border-purple-500/50"></div>
            </div>
          </div>
        </div>
      </section>

      {/* Scatter Control Trade-offs */}
      <section className="claude-surface p-8 stagger">
        <h2 className="text-2xl font-bold text-white mb-6 uppercase tracking-wider text-red-400 flex items-center gap-3">
           <AlertCircle className="text-red-500" /> Scatter Rejection Trade-offs
        </h2>
        
        <p className="text-slate-300 text-sm leading-relaxed mb-6">
          Compton scattering degrades image contrast. We employ mechanical methods to reject scattered photons before they hit the detector, but these methods come with significant dose or geometry penalties.
        </p>

        <div className="grid md:grid-cols-3 gap-4">
           <div className="bg-slate-900 border border-slate-700 p-5 rounded-xl">
              <h3 className="text-white font-bold text-sm mb-3">Anti-Scatter Grids</h3>
              <p className="text-xs text-slate-400 mb-4 leading-relaxed">
                Alternating strips of lead and radiolucent spacers. Scatters hit the lead; straight rays pass through.
              </p>
              <div className="pt-4 border-t border-slate-800">
                <span className="text-[10px] text-red-400 font-bold uppercase">The Cost</span>
                <p className="text-xs text-slate-300 mt-1">
                  Grid Conversion Factor (GCF): Blocks primary rays too! Requires <strong>3x to 8x higher mA</strong> (massive dose increase).
                </p>
              </div>
           </div>

           <div className="bg-slate-900 border border-slate-700 p-5 rounded-xl">
              <h3 className="text-white font-bold text-sm mb-3">Air-Gap Technique</h3>
              <p className="text-xs text-slate-400 mb-4 leading-relaxed">
                Moving the patient further from the detector allows scattered photons to miss the cassette entirely.
              </p>
              <div className="pt-4 border-t border-slate-800">
                <span className="text-[10px] text-red-400 font-bold uppercase">The Cost</span>
                <p className="text-xs text-slate-300 mt-1">
                  Increases <strong>Geometric Magnification & Penumbra (Blur)</strong> because the object is far from the detector.
                </p>
              </div>
           </div>

           <div className="bg-slate-900 border border-slate-700 p-5 rounded-xl">
              <h3 className="text-white font-bold text-sm mb-3">Scanning Slits</h3>
              <p className="text-xs text-slate-400 mb-4 leading-relaxed">
                A moving slit collimator ensures only a tiny sliver of tissue is irradiated at a time (&gt;95% scatter reduction).
              </p>
              <div className="pt-4 border-t border-slate-800">
                <span className="text-[10px] text-red-400 font-bold uppercase">The Cost</span>
                <p className="text-xs text-slate-300 mt-1">
                  Mechanically complex and very slow scan times, making it highly susceptible to <strong>patient motion blurring</strong>.
                </p>
              </div>
           </div>
        </div>
      </section>

      {/* Detector Generations */}
      <section className="space-y-6 stagger mt-12 border-t-2 border-slate-800 pt-10">
        <span className="claude-kicker text-emerald-400">Hardware Evolution</span>
        <h2 className="text-3xl font-bold text-white">Flat-Panel Digital Detectors</h2>

        <div className="grid lg:grid-cols-2 gap-8">
          <div className="claude-panel p-8 space-y-6">
            <h3 className="text-xl font-bold text-emerald-400 mb-2 italic flex items-center gap-2">
              <Layers className="w-5 h-5" /> Indirect Conversion (a-Si)
            </h3>
            <p className="text-slate-300 text-sm leading-relaxed mb-4">
              Step 1: X-rays hit a CsI:Tl scintillator layer, producing light.<br/>
              Step 2: Photodiodes in an amorphous Silicon (a-Si) TFT array capture the light and store the electrons.
            </p>
            <div className="claude-note border-l-slate-500 bg-slate-950/40 text-slate-300">
              <strong>Drawback:</strong> Light spreads out isotropically inside the scintillator before hitting the diode, creating a loss of spatial resolution (blur). Structured CsI acts like fiber optics to reduce this.
            </div>
            
            <div className="h-px w-full bg-slate-800 my-6"></div>

            <h3 className="text-xl font-bold text-blue-400 mb-2 italic flex items-center gap-2">
              <Waves className="w-5 h-5" /> Direct Conversion (a-Se)
            </h3>
            <p className="text-slate-300 text-sm leading-relaxed mb-4">
              X-rays hit amorphous Selenium (a-Se) directly, creating electron-hole pairs <em>with no intermediary light step</em>. An electric field pulls the electrons straight down to the storage capacitor.
            </p>
             <div className="claude-note border-l-blue-500 bg-blue-950/20 text-blue-200">
              <strong>Advantage:</strong> Exceptional spatial resolution (sharper images) because electric fields prevent lateral spreading of the signal.
            </div>
          </div>

          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-800 p-8 rounded-xl h-full flex flex-col justify-center gap-8 shadow-inner">
               <h3 className="text-white font-bold text-center text-sm uppercase tracking-widest mb-2">Geometric Vignetting Math</h3>
               <p className="text-sm text-slate-400 leading-relaxed">
                 Due to the diverging geometry of the X-ray cone, the edges of the detector receive fewer X-rays (intensity drops drop off by <Latex formula="\cos^2 \theta" />). 
               </p>
               <div className="bg-slate-950 p-6 rounded-lg border border-slate-800">
                  <Latex formula={String.raw`I_r = I_0 \cos^2 \theta \quad \text{where} \quad \cos \theta = \frac{d}{r}`} displayMode />
               </div>
               <p className="text-[10px] text-slate-500 text-center px-6">
                 If uncorrected, radiographs would show unnatural darkening at the peripheries. Flat-field calibration software automatically corrects this geometric drop-off today.
               </p>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
}
